// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userfile.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_userfile_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_userfile_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_userfile_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_userfile_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_userfile_2eproto;
namespace usern {
class userarray;
struct userarrayDefaultTypeInternal;
extern userarrayDefaultTypeInternal _userarray_default_instance_;
class userdata;
struct userdataDefaultTypeInternal;
extern userdataDefaultTypeInternal _userdata_default_instance_;
}  // namespace usern
PROTOBUF_NAMESPACE_OPEN
template<> ::usern::userarray* Arena::CreateMaybeMessage<::usern::userarray>(Arena*);
template<> ::usern::userdata* Arena::CreateMaybeMessage<::usern::userdata>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace usern {

// ===================================================================

class userdata final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:usern.userdata) */ {
 public:
  inline userdata() : userdata(nullptr) {}
  ~userdata() override;
  explicit PROTOBUF_CONSTEXPR userdata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  userdata(const userdata& from);
  userdata(userdata&& from) noexcept
    : userdata() {
    *this = ::std::move(from);
  }

  inline userdata& operator=(const userdata& from) {
    CopyFrom(from);
    return *this;
  }
  inline userdata& operator=(userdata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const userdata& default_instance() {
    return *internal_default_instance();
  }
  static inline const userdata* internal_default_instance() {
    return reinterpret_cast<const userdata*>(
               &_userdata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(userdata& a, userdata& b) {
    a.Swap(&b);
  }
  inline void Swap(userdata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(userdata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  userdata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<userdata>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const userdata& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const userdata& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(userdata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "usern.userdata";
  }
  protected:
  explicit userdata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kLocationFieldNumber = 2,
    kEmailFieldNumber = 3,
    kPasswordFieldNumber = 4,
    kAddressFieldNumber = 6,
    kPhonenumberFieldNumber = 7,
    kIdFieldNumber = 5,
  };
  // optional string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional string location = 2;
  bool has_location() const;
  private:
  bool _internal_has_location() const;
  public:
  void clear_location();
  const std::string& location() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_location(ArgT0&& arg0, ArgT... args);
  std::string* mutable_location();
  PROTOBUF_NODISCARD std::string* release_location();
  void set_allocated_location(std::string* location);
  private:
  const std::string& _internal_location() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_location(const std::string& value);
  std::string* _internal_mutable_location();
  public:

  // optional string email = 3;
  bool has_email() const;
  private:
  bool _internal_has_email() const;
  public:
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // optional string password = 4;
  bool has_password() const;
  private:
  bool _internal_has_password() const;
  public:
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // optional string address = 6;
  bool has_address() const;
  private:
  bool _internal_has_address() const;
  public:
  void clear_address();
  const std::string& address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_address();
  PROTOBUF_NODISCARD std::string* release_address();
  void set_allocated_address(std::string* address);
  private:
  const std::string& _internal_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // optional string phonenumber = 7;
  bool has_phonenumber() const;
  private:
  bool _internal_has_phonenumber() const;
  public:
  void clear_phonenumber();
  const std::string& phonenumber() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_phonenumber(ArgT0&& arg0, ArgT... args);
  std::string* mutable_phonenumber();
  PROTOBUF_NODISCARD std::string* release_phonenumber();
  void set_allocated_phonenumber(std::string* phonenumber);
  private:
  const std::string& _internal_phonenumber() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_phonenumber(const std::string& value);
  std::string* _internal_mutable_phonenumber();
  public:

  // optional int32 id = 5;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:usern.userdata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr location_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr phonenumber_;
  int32_t id_;
  friend struct ::TableStruct_userfile_2eproto;
};
// -------------------------------------------------------------------

class userarray final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:usern.userarray) */ {
 public:
  inline userarray() : userarray(nullptr) {}
  ~userarray() override;
  explicit PROTOBUF_CONSTEXPR userarray(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  userarray(const userarray& from);
  userarray(userarray&& from) noexcept
    : userarray() {
    *this = ::std::move(from);
  }

  inline userarray& operator=(const userarray& from) {
    CopyFrom(from);
    return *this;
  }
  inline userarray& operator=(userarray&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const userarray& default_instance() {
    return *internal_default_instance();
  }
  static inline const userarray* internal_default_instance() {
    return reinterpret_cast<const userarray*>(
               &_userarray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(userarray& a, userarray& b) {
    a.Swap(&b);
  }
  inline void Swap(userarray* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(userarray* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  userarray* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<userarray>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const userarray& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const userarray& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(userarray* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "usern.userarray";
  }
  protected:
  explicit userarray(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserlistFieldNumber = 1,
    kUsercountFieldNumber = 2,
  };
  // repeated .usern.userdata userlist = 1;
  int userlist_size() const;
  private:
  int _internal_userlist_size() const;
  public:
  void clear_userlist();
  ::usern::userdata* mutable_userlist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::usern::userdata >*
      mutable_userlist();
  private:
  const ::usern::userdata& _internal_userlist(int index) const;
  ::usern::userdata* _internal_add_userlist();
  public:
  const ::usern::userdata& userlist(int index) const;
  ::usern::userdata* add_userlist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::usern::userdata >&
      userlist() const;

  // optional int32 usercount = 2;
  bool has_usercount() const;
  private:
  bool _internal_has_usercount() const;
  public:
  void clear_usercount();
  int32_t usercount() const;
  void set_usercount(int32_t value);
  private:
  int32_t _internal_usercount() const;
  void _internal_set_usercount(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:usern.userarray)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::usern::userdata > userlist_;
  int32_t usercount_;
  friend struct ::TableStruct_userfile_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// userdata

// optional string name = 1;
inline bool userdata::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool userdata::has_name() const {
  return _internal_has_name();
}
inline void userdata::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& userdata::name() const {
  // @@protoc_insertion_point(field_get:usern.userdata.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void userdata::set_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:usern.userdata.name)
}
inline std::string* userdata::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:usern.userdata.name)
  return _s;
}
inline const std::string& userdata::_internal_name() const {
  return name_.Get();
}
inline void userdata::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* userdata::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* userdata::release_name() {
  // @@protoc_insertion_point(field_release:usern.userdata.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = name_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void userdata::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:usern.userdata.name)
}

// optional string location = 2;
inline bool userdata::_internal_has_location() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool userdata::has_location() const {
  return _internal_has_location();
}
inline void userdata::clear_location() {
  location_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& userdata::location() const {
  // @@protoc_insertion_point(field_get:usern.userdata.location)
  return _internal_location();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void userdata::set_location(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 location_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:usern.userdata.location)
}
inline std::string* userdata::mutable_location() {
  std::string* _s = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:usern.userdata.location)
  return _s;
}
inline const std::string& userdata::_internal_location() const {
  return location_.Get();
}
inline void userdata::_internal_set_location(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  location_.Set(value, GetArenaForAllocation());
}
inline std::string* userdata::_internal_mutable_location() {
  _has_bits_[0] |= 0x00000002u;
  return location_.Mutable(GetArenaForAllocation());
}
inline std::string* userdata::release_location() {
  // @@protoc_insertion_point(field_release:usern.userdata.location)
  if (!_internal_has_location()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = location_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (location_.IsDefault()) {
    location_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void userdata::set_allocated_location(std::string* location) {
  if (location != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  location_.SetAllocated(location, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (location_.IsDefault()) {
    location_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:usern.userdata.location)
}

// optional string email = 3;
inline bool userdata::_internal_has_email() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool userdata::has_email() const {
  return _internal_has_email();
}
inline void userdata::clear_email() {
  email_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& userdata::email() const {
  // @@protoc_insertion_point(field_get:usern.userdata.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void userdata::set_email(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:usern.userdata.email)
}
inline std::string* userdata::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:usern.userdata.email)
  return _s;
}
inline const std::string& userdata::_internal_email() const {
  return email_.Get();
}
inline void userdata::_internal_set_email(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  email_.Set(value, GetArenaForAllocation());
}
inline std::string* userdata::_internal_mutable_email() {
  _has_bits_[0] |= 0x00000004u;
  return email_.Mutable(GetArenaForAllocation());
}
inline std::string* userdata::release_email() {
  // @@protoc_insertion_point(field_release:usern.userdata.email)
  if (!_internal_has_email()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = email_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (email_.IsDefault()) {
    email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void userdata::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (email_.IsDefault()) {
    email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:usern.userdata.email)
}

// optional string password = 4;
inline bool userdata::_internal_has_password() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool userdata::has_password() const {
  return _internal_has_password();
}
inline void userdata::clear_password() {
  password_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& userdata::password() const {
  // @@protoc_insertion_point(field_get:usern.userdata.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void userdata::set_password(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:usern.userdata.password)
}
inline std::string* userdata::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:usern.userdata.password)
  return _s;
}
inline const std::string& userdata::_internal_password() const {
  return password_.Get();
}
inline void userdata::_internal_set_password(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  password_.Set(value, GetArenaForAllocation());
}
inline std::string* userdata::_internal_mutable_password() {
  _has_bits_[0] |= 0x00000008u;
  return password_.Mutable(GetArenaForAllocation());
}
inline std::string* userdata::release_password() {
  // @@protoc_insertion_point(field_release:usern.userdata.password)
  if (!_internal_has_password()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  auto* p = password_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault()) {
    password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void userdata::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault()) {
    password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:usern.userdata.password)
}

// optional int32 id = 5;
inline bool userdata::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool userdata::has_id() const {
  return _internal_has_id();
}
inline void userdata::clear_id() {
  id_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline int32_t userdata::_internal_id() const {
  return id_;
}
inline int32_t userdata::id() const {
  // @@protoc_insertion_point(field_get:usern.userdata.id)
  return _internal_id();
}
inline void userdata::_internal_set_id(int32_t value) {
  _has_bits_[0] |= 0x00000040u;
  id_ = value;
}
inline void userdata::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:usern.userdata.id)
}

// optional string address = 6;
inline bool userdata::_internal_has_address() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool userdata::has_address() const {
  return _internal_has_address();
}
inline void userdata::clear_address() {
  address_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& userdata::address() const {
  // @@protoc_insertion_point(field_get:usern.userdata.address)
  return _internal_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void userdata::set_address(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000010u;
 address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:usern.userdata.address)
}
inline std::string* userdata::mutable_address() {
  std::string* _s = _internal_mutable_address();
  // @@protoc_insertion_point(field_mutable:usern.userdata.address)
  return _s;
}
inline const std::string& userdata::_internal_address() const {
  return address_.Get();
}
inline void userdata::_internal_set_address(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  address_.Set(value, GetArenaForAllocation());
}
inline std::string* userdata::_internal_mutable_address() {
  _has_bits_[0] |= 0x00000010u;
  return address_.Mutable(GetArenaForAllocation());
}
inline std::string* userdata::release_address() {
  // @@protoc_insertion_point(field_release:usern.userdata.address)
  if (!_internal_has_address()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  auto* p = address_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (address_.IsDefault()) {
    address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void userdata::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  address_.SetAllocated(address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (address_.IsDefault()) {
    address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:usern.userdata.address)
}

// optional string phonenumber = 7;
inline bool userdata::_internal_has_phonenumber() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool userdata::has_phonenumber() const {
  return _internal_has_phonenumber();
}
inline void userdata::clear_phonenumber() {
  phonenumber_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& userdata::phonenumber() const {
  // @@protoc_insertion_point(field_get:usern.userdata.phonenumber)
  return _internal_phonenumber();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void userdata::set_phonenumber(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000020u;
 phonenumber_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:usern.userdata.phonenumber)
}
inline std::string* userdata::mutable_phonenumber() {
  std::string* _s = _internal_mutable_phonenumber();
  // @@protoc_insertion_point(field_mutable:usern.userdata.phonenumber)
  return _s;
}
inline const std::string& userdata::_internal_phonenumber() const {
  return phonenumber_.Get();
}
inline void userdata::_internal_set_phonenumber(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  phonenumber_.Set(value, GetArenaForAllocation());
}
inline std::string* userdata::_internal_mutable_phonenumber() {
  _has_bits_[0] |= 0x00000020u;
  return phonenumber_.Mutable(GetArenaForAllocation());
}
inline std::string* userdata::release_phonenumber() {
  // @@protoc_insertion_point(field_release:usern.userdata.phonenumber)
  if (!_internal_has_phonenumber()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  auto* p = phonenumber_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (phonenumber_.IsDefault()) {
    phonenumber_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void userdata::set_allocated_phonenumber(std::string* phonenumber) {
  if (phonenumber != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  phonenumber_.SetAllocated(phonenumber, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (phonenumber_.IsDefault()) {
    phonenumber_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:usern.userdata.phonenumber)
}

// -------------------------------------------------------------------

// userarray

// repeated .usern.userdata userlist = 1;
inline int userarray::_internal_userlist_size() const {
  return userlist_.size();
}
inline int userarray::userlist_size() const {
  return _internal_userlist_size();
}
inline void userarray::clear_userlist() {
  userlist_.Clear();
}
inline ::usern::userdata* userarray::mutable_userlist(int index) {
  // @@protoc_insertion_point(field_mutable:usern.userarray.userlist)
  return userlist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::usern::userdata >*
userarray::mutable_userlist() {
  // @@protoc_insertion_point(field_mutable_list:usern.userarray.userlist)
  return &userlist_;
}
inline const ::usern::userdata& userarray::_internal_userlist(int index) const {
  return userlist_.Get(index);
}
inline const ::usern::userdata& userarray::userlist(int index) const {
  // @@protoc_insertion_point(field_get:usern.userarray.userlist)
  return _internal_userlist(index);
}
inline ::usern::userdata* userarray::_internal_add_userlist() {
  return userlist_.Add();
}
inline ::usern::userdata* userarray::add_userlist() {
  ::usern::userdata* _add = _internal_add_userlist();
  // @@protoc_insertion_point(field_add:usern.userarray.userlist)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::usern::userdata >&
userarray::userlist() const {
  // @@protoc_insertion_point(field_list:usern.userarray.userlist)
  return userlist_;
}

// optional int32 usercount = 2;
inline bool userarray::_internal_has_usercount() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool userarray::has_usercount() const {
  return _internal_has_usercount();
}
inline void userarray::clear_usercount() {
  usercount_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline int32_t userarray::_internal_usercount() const {
  return usercount_;
}
inline int32_t userarray::usercount() const {
  // @@protoc_insertion_point(field_get:usern.userarray.usercount)
  return _internal_usercount();
}
inline void userarray::_internal_set_usercount(int32_t value) {
  _has_bits_[0] |= 0x00000001u;
  usercount_ = value;
}
inline void userarray::set_usercount(int32_t value) {
  _internal_set_usercount(value);
  // @@protoc_insertion_point(field_set:usern.userarray.usercount)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace usern

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_userfile_2eproto
